version: '3'

services:
  churh_sass:  
    build:
      context: .
      args:
        - PORT=${PORT}
    container_name: churh_sass
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env.dev